import React, { useMemo, useRef } from 'react';
import { FaceSettings, PrintAsset, PrintFaceMode, PrintPlacement } from './PrintDesign';
import { garmentPath, necklinePath, specialDesignLines } from './garmentGeometry';
import { useLanguage } from './Language';

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));

export function GarmentPreview({ composition, family, neckline, sleeve, special, garmentColor = '#ffffff', assets, selectedAssetId, mode, view, setView, settings, updateSettings, placements, activePlacementId, setActivePlacementId, updatePlacement, addPlacement, guidesEnabled }: {
  composition?: { recipe_hash: string; pieces: { role: string; width_mm?: number; height_mm?: number }[] }; family: 'tshirt' | 'shirt'; neckline: string; sleeve: string; special?: string; garmentColor?: string; assets: PrintAsset[]; selectedAssetId: string; mode: PrintFaceMode; view: 'front' | 'back'; setView: (view: 'front' | 'back') => void; settings: FaceSettings; updateSettings: (patch: Partial<FaceSettings>) => void; placements: PrintPlacement[]; activePlacementId: string | null; setActivePlacementId: (id: string | null) => void; updatePlacement: (id: string, patch: Partial<PrintPlacement>) => void; addPlacement: (view: 'front' | 'back', x: number, y: number) => void; guidesEnabled?: boolean;
}) {
  const { t } = useLanguage();
  const svgRef = useRef<SVGSVGElement | null>(null);
  const drag = useRef<{ kind: 'density' | 'placement' | 'scale' | 'crop' | 'rotate'; pointerX?: number; pointerY?: number; x?: number; y?: number; id?: string; centerX?: number; centerY?: number; distance?: number; size?: number; edge?: 'left' | 'right' | 'top' | 'bottom'; localX?: number; localY?: number; cropValue?: number; rotation?: number; angle?: number } | null>(null);
  const bodyPiece = composition?.pieces.find((piece) => piece.role === 'front_body' || piece.role === 'front_left');
  const sleevePiece = composition?.pieces.find((piece) => piece.role === 'sleeve' || piece.role === 'sleeve_left');
  const sleeveLongEdge = Math.max(sleevePiece?.width_mm || 0, sleevePiece?.height_mm || 0);
  const bodyLongEdge = Math.max(bodyPiece?.width_mm || 0, bodyPiece?.height_mm || 1);
  const longFromDxf = sleeve === 'short' || sleeve === 'sleeveless' ? false : family === 'shirt' || sleeveLongEdge > bodyLongEdge * .72;
  const path = useMemo(() => garmentPath(family, sleeve, longFromDxf), [family, sleeve, longFromDxf]);
  const neck = useMemo(() => necklinePath(neckline, view), [neckline, view]);
  const detailLines = useMemo(() => view === 'front' ? specialDesignLines(special || '') : [], [special, view]);
  const sleeveLabel = sleeve === 'puff' ? t('泡泡袖', 'Puff sleeve') : sleeve === 'bell' ? t('喇叭袖', 'Bell sleeve') : sleeve === 'flutter' ? t('飞袖', 'Flutter sleeve') : sleeve === 'batwing' ? t('蝙蝠袖', 'Batwing sleeve') : sleeve === 'sleeveless' ? t('无袖试样', 'Sleeveless trial') : longFromDxf ? t('长袖', 'Long sleeve') : t('短袖', 'Short sleeve');
  const currentAsset = assets.find((item) => item.id === selectedAssetId) || assets[0];
  const visiblePlacements = placements.filter((item) => item.view === view);
  const baseSpacing = clamp(190 - Math.sqrt(settings.density) * 6.5, 34, 150);
  const spacing = clamp(baseSpacing + (settings.gap || 0), 34, 270);
  const motif = baseSpacing * clamp(settings.size / 100, .18, 1.3);
  const toGarmentPoint = (event: React.PointerEvent | React.MouseEvent) => {
    const rect = svgRef.current?.getBoundingClientRect(); if (!rect) return { x: 50, y: 50 };
    const svgX = (event.clientX - rect.left) / rect.width * 600;
    const svgY = (event.clientY - rect.top) / rect.height * 760;
    return { x: clamp((svgX - 140) / 320 * 100, 0, 100), y: clamp((svgY - 105) / 580 * 100, 0, 100) };
  };
  const toSvgPoint = (event: React.PointerEvent | React.MouseEvent) => { const rect = svgRef.current?.getBoundingClientRect(); if (!rect) return { x: 300, y: 380 }; return { x: (event.clientX - rect.left) / rect.width * 600, y: (event.clientY - rect.top) / rect.height * 760 }; };
  const toLocalPoint = (event: React.PointerEvent | React.MouseEvent, centerX: number, centerY: number, rotation: number) => { const point = toSvgPoint(event); const angle = -rotation * Math.PI / 180; const dx = point.x - centerX; const dy = point.y - centerY; return { x: dx * Math.cos(angle) - dy * Math.sin(angle), y: dx * Math.sin(angle) + dy * Math.cos(angle) }; };
  const startDensity = (event: React.PointerEvent<SVGSVGElement>) => { if (mode !== 'density') return; const pointer = toGarmentPoint(event); drag.current = { kind: 'density', pointerX: pointer.x, pointerY: pointer.y, x: settings.x, y: settings.y }; event.currentTarget.setPointerCapture(event.pointerId); };
  const startPlacement = (event: React.PointerEvent<SVGImageElement>, placement: PrintPlacement) => { event.stopPropagation(); const pointer = toGarmentPoint(event); setActivePlacementId(placement.id); drag.current = { kind: 'placement', id: placement.id, pointerX: pointer.x, pointerY: pointer.y, x: placement.x, y: placement.y }; event.currentTarget.setPointerCapture(event.pointerId); };
  const startScale = (event: React.PointerEvent<SVGCircleElement>, placement: PrintPlacement) => { event.stopPropagation(); const centerX = 140 + placement.x / 100 * 320; const centerY = 105 + placement.y / 100 * 580; const point = toSvgPoint(event); drag.current = { kind: 'scale', id: placement.id, centerX, centerY, distance: Math.max(Math.hypot(point.x - centerX, point.y - centerY), 1), size: placement.size }; event.currentTarget.setPointerCapture(event.pointerId); };
  const startRotate = (event: React.PointerEvent<SVGCircleElement>, placement: PrintPlacement) => { event.stopPropagation(); const centerX = 140 + placement.x / 100 * 320; const centerY = 105 + placement.y / 100 * 580; const point = toSvgPoint(event); drag.current = { kind: 'rotate', id: placement.id, centerX, centerY, angle: Math.atan2(point.y - centerY, point.x - centerX) * 180 / Math.PI, rotation: placement.rotation }; event.currentTarget.setPointerCapture(event.pointerId); };
  const startCrop = (event: React.PointerEvent<SVGRectElement>, placement: PrintPlacement, edge: 'left' | 'right' | 'top' | 'bottom') => { event.stopPropagation(); const centerX = 140 + placement.x / 100 * 320; const centerY = 105 + placement.y / 100 * 580; const local = toLocalPoint(event, centerX, centerY, placement.rotation); const cropValue = edge === 'left' ? placement.cropLeft : edge === 'right' ? placement.cropRight : edge === 'top' ? placement.cropTop : placement.cropBottom; drag.current = { kind: 'crop', id: placement.id, centerX, centerY, edge, localX: local.x, localY: local.y, cropValue: cropValue || 0, size: placement.size, rotation: placement.rotation }; event.currentTarget.setPointerCapture(event.pointerId); };
  const move = (event: React.PointerEvent<SVGSVGElement>) => {
    if (!drag.current) return;
    if (drag.current.kind === 'scale' && drag.current.id && drag.current.centerX != null && drag.current.centerY != null) { const point = toSvgPoint(event); const distance = Math.hypot(point.x - drag.current.centerX, point.y - drag.current.centerY); updatePlacement(drag.current.id, { size: clamp((drag.current.size || 32) * distance / (drag.current.distance || 1), 8, 240) }); return; }
    if (drag.current.kind === 'rotate' && drag.current.id && drag.current.centerX != null && drag.current.centerY != null) { const point = toSvgPoint(event); const angle = Math.atan2(point.y - drag.current.centerY, point.x - drag.current.centerX) * 180 / Math.PI; let rotation = (drag.current.rotation || 0) + angle - (drag.current.angle || 0); rotation = ((rotation + 180) % 360 + 360) % 360 - 180; updatePlacement(drag.current.id, { rotation }); return; }
    if (drag.current.kind === 'crop' && drag.current.id && drag.current.centerX != null && drag.current.centerY != null && drag.current.edge) { const local = toLocalPoint(event, drag.current.centerX, drag.current.centerY, drag.current.rotation || 0); const width = (drag.current.size || 32) * 2.2; const axisDelta = drag.current.edge === 'left' || drag.current.edge === 'right' ? local.x - (drag.current.localX || 0) : local.y - (drag.current.localY || 0); const direction = drag.current.edge === 'right' || drag.current.edge === 'bottom' ? -1 : 1; const value = clamp((drag.current.cropValue || 0) + direction * axisDelta / width * 100, 0, 45); updatePlacement(drag.current.id, { [drag.current.edge === 'left' ? 'cropLeft' : drag.current.edge === 'right' ? 'cropRight' : drag.current.edge === 'top' ? 'cropTop' : 'cropBottom']: value }); return; }
    const pointer = toGarmentPoint(event); const x = clamp((drag.current.x || 0) + pointer.x - (drag.current.pointerX || 0), 0, 100); const y = clamp((drag.current.y || 0) + pointer.y - (drag.current.pointerY || 0), 0, 100);
    if (drag.current.kind === 'density') updateSettings({ x, y }); else if (drag.current.id) updatePlacement(drag.current.id, { x, y });
  };
  const addAtPointer = (event: React.MouseEvent<SVGSVGElement>) => { if (mode !== 'manual') return; event.preventDefault(); const point = toGarmentPoint(event); addPlacement(view, point.x, point.y); };
  const wheelEditor = (event: React.WheelEvent<SVGSVGElement>) => {
    if (mode !== 'density') return;
    event.preventDefault();
    if (event.shiftKey) updateSettings({ density: clamp(Math.round(settings.density * (event.deltaY < 0 ? 1.12 : .89)), 10, 500) });
    else updateSettings({ size: clamp(settings.size * (event.deltaY < 0 ? 1.08 : .92), 15, 130) });
  };
  return <div className="print-workbench-redesign">
    <div className="print-canvas-header"><div><span>{t('2D 服装印花图', '2D Garment Print')}</span><small>{family === 'shirt' ? t('衬衫', 'Shirt') : t('T恤', 'T-shirt')} · {sleeveLabel} · {view === 'front' ? t('正面', 'Front') : t('背面', 'Back')}</small></div><div className="face-switch"><button className={view === 'front' ? 'active' : ''} onClick={() => setView('front')}>{t('正面设计', 'Front')}</button><button className={view === 'back' ? 'active' : ''} onClick={() => setView('back')}>{t('背面设计', 'Back')}</button></div></div>
    <div className="print-editor-stage"><svg ref={svgRef} className="garment-blueprint" viewBox="0 0 600 760" onPointerDown={startDensity} onPointerMove={move} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }} onContextMenu={addAtPointer} onWheel={wheelEditor}>
      <defs><mask id="garment-mask"><rect width="600" height="760" fill="black" /><path d={path} fill="white" /><path d={neck} fill="black" /></mask><pattern id="density-pattern" patternUnits="userSpaceOnUse" width={spacing} height={spacing} x={(settings.x - 50) * 1.2} y={(settings.y - 50) * 1.2} patternTransform={`rotate(${settings.rotation} 300 380)`}>{currentAsset && <image href={currentAsset.src} x={(spacing - motif) / 2} y={(spacing - motif) / 2} width={motif} height={motif} preserveAspectRatio="xMidYMid meet" />}</pattern>{visiblePlacements.map((placement) => { const width = placement.size * 2.2; const left = 140 + placement.x / 100 * 320 - width / 2 + width * (placement.cropLeft || 0) / 100; const top = 105 + placement.y / 100 * 580 - width / 2 + width * (placement.cropTop || 0) / 100; const cropWidth = width * (100 - (placement.cropLeft || 0) - (placement.cropRight || 0)) / 100; const cropHeight = width * (100 - (placement.cropTop || 0) - (placement.cropBottom || 0)) / 100; return <clipPath id={`crop-${placement.id}`} key={`crop-${placement.id}`}><rect x={left} y={top} width={cropWidth} height={cropHeight} /></clipPath>; })}</defs>
      <g mask="url(#garment-mask)"><path d={path} fill={garmentColor} />{mode === 'density' && <path d={path} fill="url(#density-pattern)" />}{mode === 'manual' && visiblePlacements.map((placement) => { const asset = assets.find((item) => item.id === placement.assetId); const width = placement.size * 2.2; const height = width; const centerX = 140 + placement.x / 100 * 320; const centerY = 105 + placement.y / 100 * 580; return asset ? <image key={placement.id} href={asset.src} x={centerX - width / 2} y={centerY - height / 2} width={width} height={height} preserveAspectRatio="xMidYMid meet" clipPath={`url(#crop-${placement.id})`} transform={`rotate(${placement.rotation} ${centerX} ${centerY})`} onPointerDown={(event) => startPlacement(event, placement)} onWheel={(event) => { event.preventDefault(); event.stopPropagation(); setActivePlacementId(placement.id); updatePlacement(placement.id, { size: clamp(placement.size * (event.deltaY < 0 ? 1.08 : .92), 8, 240) }); }} /> : null; })}</g>
      <path d={path} fill="none" stroke="#6e7182" strokeWidth="2.2" /><path d={neck} fill="none" stroke="#6e7182" strokeWidth="2.2" />{detailLines.map((line, index) => <path key={`detail-${index}`} d={line.d} fill="none" stroke="#9b75b8" strokeWidth="3" strokeDasharray={line.dashed ? '7 5' : undefined} />)}{family === 'shirt' && <><line x1="300" y1="112" x2="300" y2="718" stroke="#b6b7c1" strokeDasharray="8 7" /><circle cx="300" cy="220" r="3" fill="#8f87a0" /><circle cx="300" cy="310" r="3" fill="#8f87a0" /><circle cx="300" cy="400" r="3" fill="#8f87a0" /></>}
      {guidesEnabled && <g className="print-guides" aria-label={t('印花辅助线', 'Print guides')}><line x1="300" y1="92" x2="300" y2="714" /><line x1="145" y1="380" x2="455" y2="380" /><circle cx="300" cy="380" r="7" /></g>}
      {mode === 'manual' && visiblePlacements.filter((item) => item.id === activePlacementId).map((placement) => { const width = placement.size * 2.2; const centerX = 140 + placement.x / 100 * 320; const centerY = 105 + placement.y / 100 * 580; const left = centerX - width / 2 + width * (placement.cropLeft || 0) / 100; const right = centerX + width / 2 - width * (placement.cropRight || 0) / 100; const top = centerY - width / 2 + width * (placement.cropTop || 0) / 100; const bottom = centerY + width / 2 - width * (placement.cropBottom || 0) / 100; const rotateY = top - 34; return <g key={`anchor-${placement.id}`} className="placement-anchors" transform={`rotate(${placement.rotation} ${centerX} ${centerY})`}><rect className="selection-frame" x={left} y={top} width={right - left} height={bottom - top} /><line className="rotate-stem" x1={centerX} y1={top} x2={centerX} y2={rotateY} /><circle className="rotate-handle" aria-label="拖动旋转图案" cx={centerX} cy={rotateY} r="9" onPointerDown={(event) => startRotate(event, placement)} />{[[left, top], [right, top], [left, bottom], [right, bottom]].map(([x, y], index) => <circle className="scale-handle" aria-label="拖动缩放图案" key={`scale-${index}`} cx={x} cy={y} r="8" onPointerDown={(event) => startScale(event, placement)} />)}<rect className="crop-handle crop-left" aria-label="拖动裁剪左侧" x={left - 6} y={(top + bottom) / 2 - 12} width="12" height="24" onPointerDown={(event) => startCrop(event, placement, 'left')} /><rect className="crop-handle crop-right" aria-label="拖动裁剪右侧" x={right - 6} y={(top + bottom) / 2 - 12} width="12" height="24" onPointerDown={(event) => startCrop(event, placement, 'right')} /><rect className="crop-handle crop-top" aria-label="拖动裁剪上方" x={(left + right) / 2 - 12} y={top - 6} width="24" height="12" onPointerDown={(event) => startCrop(event, placement, 'top')} /><rect className="crop-handle crop-bottom" aria-label="拖动裁剪下方" x={(left + right) / 2 - 12} y={bottom - 6} width="24" height="12" onPointerDown={(event) => startCrop(event, placement, 'bottom')} /></g>; })}
    </svg><div className="print-editor-help">{mode === 'manual' ? '拖动图案移动 · 顶部圆点旋转 · 四角缩放 · 橙色边点裁剪 · 滚轮缩放' : mode === 'density' ? '拖动阵列 · 滚轮调大小 · Shift + 滚轮调密度' : `当前${view === 'front' ? '正面' : '背面'}无印花`}</div></div>
  </div>;
}
